# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cutterandcropper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!

  # Pods for Cutterandcropper


  #use_native_modules!
  pod 'CropViewController', :git => 'https://github.com/wammy67/TOCropViewController'
    end
    

